# Generated by Django 5.0 on 2023-12-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_btc', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ValorHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_timestamp', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('marketcap', models.FloatField()),
                ('btc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BitcoinApp.bitcoin')),
            ],
            options={
                'ordering': ('day_timestamp',),
            },
        ),
    ]
