# Generated by Django 5.0 on 2023-12-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitcoinApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='id_btc',
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
