# Generated by Django 5.0 on 2023-12-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitcoinApp', '0002_remove_bitcoin_id_btc_alter_bitcoin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorhistorico',
            name='day_timestamp',
            field=models.DateField(),
        ),
    ]
