# Generated by Django 5.0 on 2023-12-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitcoinApp', '0003_alter_valorhistorico_day_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorhistorico',
            options={'ordering': ('day',)},
        ),
        migrations.RenameField(
            model_name='valorhistorico',
            old_name='day_timestamp',
            new_name='day',
        ),
    ]
